### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [bobrowskibiz/kod8.8#1]
- [x] slowa kluczowego `var` uzywa sie tylko raz, jak pierwszy raz deklarujesz zmienna, potem juz odwolujesz sie do samej zmiennej

`wyliczone` daje dobry wynik, ale jest to rozwiazanie na sztywno. Z kolei `wydzielone` idzie w dobrym kierunku, ale daje zly wynik
- [x] popraw ta druga opcje, aby zwracala dobry wynik https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Obiekty/String/substr

- [x] angielskie nazwy pliz, dla wprawy :)

**Comment by bobrowskibiz** [comment]
działa :D

**Comment by zdolny** [comment]
Jest juz prawie dobrze, ale:
- [ ] do metody `substr` jako pierwszy parametr przekazujesz zmienna `length`, ktorej nigdzie nie masz zdefiniowanej - zerknij jeszcze raz do dokumentacji, co tam powinno byc przekazane
- [ ] w wynikowym zdaniu brakuje jednej litery na koncu. To dlatego, ze brakuje czegos w startowym zdaniu w zmiennej `text` w stosunku do tego, co jest napisane w zadaniu

**Comment by bobrowskibiz** [comment]
1. rozumiem że chodziło o zmienną text jako element jaki będzie początkowy i dzielony ?
2. rozumiem że chodziło o kropkę na końcu.

**Comment by zdolny** [comment]
obgadane, wiec zamykam
